# Generated by Django 3.0.8 on 2020-08-22 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='report_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_employee', to='empinfo.Employee'),
        ),
    ]
