# Generated by Django 3.0.8 on 2020-08-23 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empinfo', '0003_auto_20200822_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='employee',
        ),
        migrations.AlterField(
            model_name='employee',
            name='report_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporting_manager', to='empinfo.Employee'),
        ),
        migrations.CreateModel(
            name='Employeeproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empinfo.Employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empinfo.Project')),
            ],
        ),
    ]
