# Generated by Django 3.0.8 on 2020-08-23 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empinfo', '0004_auto_20200823_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeproject',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_employee', to='empinfo.Employee'),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='empinfo.Project'),
        ),
    ]
