# Generated by Django 3.0.8 on 2020-08-23 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empinfo', '0005_auto_20200823_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_main', to='empinfo.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_manager', to='empinfo.Employee'),
        ),
    ]
